main: main.Main
name: Hitw
version: 1.0
api-version: 1.13
author: Blackoutburst
description: HitW
commands:
  fly:
    description: Toggle Fly mode
    usage: /fly
  play:
    description: Start game
    usage: /play
  leave:
    description: Stop game
    usage: /leave
  l:
    description: Stop game
    usage: /l
  spawn:
    description: Teleport the player to spawn
    usage: /spawn
  discord:
    description: Give HitW discord link
    usage: /discord
  color:
    description: Teleport the player to the color editor
    usage: /color
  delay:
    description: Change the lever delay
    usage: /delay
  tourney:
    description: Tournament management
    usage: /tourney
  tournament:
    description: Tournament management
    usage: /tournament
  spectate:
    description: Spectate the tournament
    usage: /spectate
  hitw:
    description: Manage plugin
    usage: /hitw
  survival:
    description: Send you to the survival world
    usage: /survival
  title:
    description: Toggle title affichage
    usage: /title
  memtime:
    description: Change wall memory time
    usage: /memtime
  coop:
    description: Co-op commands
    usage: /coop
  p:
    description: Co-op commands
    usage: /p
